//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ShopQuanAoV2.Module.BusinessObjects.ORMDataModel1
{

    [DefaultProperty("id_mau_san_pham")]
    public partial class ChiTietSanPham : DevExpress.Persistent.BaseImpl.BaseObject
    {
        MauSanPham fid_mau_san_pham;
        [Association(@"ChiTietSanPhamReferencesMauSanPham")]
        public MauSanPham id_mau_san_pham
        {
            get { return fid_mau_san_pham; }
            set { SetPropertyValue<MauSanPham>(nameof(id_mau_san_pham), ref fid_mau_san_pham, value); }
        }
        KichCoSanPham fid_kich_co_san_pham;
        [Association(@"ChiTietSanPhamReferencesKichCoSanPham")]
        public KichCoSanPham id_kich_co_san_pham
        {
            get { return fid_kich_co_san_pham; }
            set { SetPropertyValue<KichCoSanPham>(nameof(id_kich_co_san_pham), ref fid_kich_co_san_pham, value); }
        }
        SanPham fid_san_pham;
        [Association(@"ChiTietSanPhamReferencesSanPham")]
        public SanPham id_san_pham
        {
            get { return fid_san_pham; }
            set { SetPropertyValue<SanPham>(nameof(id_san_pham), ref fid_san_pham, value); }
        }
        [Association(@"LoHangReferencesChiTietSanPham")]
        public XPCollection<LoHang> LoHangs { get { return GetCollection<LoHang>(nameof(LoHangs)); } }
    }

}
