//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
namespace ShopQuanAoV2.Module.BusinessObjects.ORMDataModel1
{

    [DefaultClassOptions]

    [DefaultProperty("trang_thai")]
    public partial class HoaDon : DevExpress.Persistent.BaseImpl.BaseObject
    {
        DateTime fngay_tao;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
        DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime ngay_tao
        {
            get { return fngay_tao; }
            set { SetPropertyValue<DateTime>(nameof(ngay_tao), ref fngay_tao, value); }
        }
        string ftrang_thai;
        public string trang_thai
        {
            get { return ftrang_thai; }
            set { SetPropertyValue<string>(nameof(trang_thai), ref ftrang_thai, value); }
        }
        int fso_phieu;
        [DevExpress.Persistent.Validation.RuleUniqueValue]
        public int so_phieu
        {
            get { return fso_phieu; }
            set { SetPropertyValue<int>(nameof(so_phieu), ref fso_phieu, value); }
        }

        public decimal tong_tien
        {
            get
            {
                decimal tien = 0;
                foreach (ChiTietHoaDon item in ChiTietHoaDons)
                {
                    tien += item.thanh_tien;
                }
                return tien;
            }
        }

        [Association(@"ChiTietHoaDonReferencesHoaDon"), Aggregated]
        public XPCollection<ChiTietHoaDon> ChiTietHoaDons { get { return GetCollection<ChiTietHoaDon>(nameof(ChiTietHoaDons)); } }
    }

}
