//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ShopQuanAoV2.Module.BusinessObjects.ORMDataModel1
{

    [DefaultProperty("ten")]
    public partial class KichCoSanPham : DevExpress.Persistent.BaseImpl.BaseObject
    {
        SanPham fid_san_pham;
        public SanPham id_san_pham
        {
            get { return fid_san_pham; }
            set { SetPropertyValue<SanPham>(nameof(id_san_pham), ref fid_san_pham, value); }
        }
        string ften;
        public string ten
        {
            get { return ften; }
            set { SetPropertyValue<string>(nameof(ten), ref ften, value); }
        }
        string fkich_co;
        public string kich_co
        {
            get { return fkich_co; }
            set { SetPropertyValue<string>(nameof(kich_co), ref fkich_co, value); }
        }
        [Association(@"ChiTietSanPhamReferencesKichCoSanPham")]
        public XPCollection<ChiTietSanPham> ChiTietSanPhams { get { return GetCollection<ChiTietSanPham>(nameof(ChiTietSanPhams)); } }
    }

}
