//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ShopQuanAoV2.Module.BusinessObjects.ORMDataModel1
{

    [DefaultProperty("mo_ta")]
    public partial class LoHang : DevExpress.Persistent.BaseImpl.BaseObject
    {
        int fso_luong_nhap;
        public int so_luong_nhap
        {
            get { return fso_luong_nhap; }
            set { SetPropertyValue<int>(nameof(so_luong_nhap), ref fso_luong_nhap, value); }
        }
        int fso_luong_con_lai;
        public int so_luong_con_lai
        {
            get { return fso_luong_con_lai; }
            set { SetPropertyValue<int>(nameof(so_luong_con_lai), ref fso_luong_con_lai, value); }
        }
        NhaCungCap fid_nha_cung_cap;
        [Association(@"LoHangReferencesNhaCungCap")]
        public NhaCungCap id_nha_cung_cap
        {
            get { return fid_nha_cung_cap; }
            set { SetPropertyValue<NhaCungCap>(nameof(id_nha_cung_cap), ref fid_nha_cung_cap, value); }
        }
        DateTime fngay_cap_nhat;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime ngay_cap_nhat
        {
            get { return fngay_cap_nhat; }
            set { SetPropertyValue<DateTime>(nameof(ngay_cap_nhat), ref fngay_cap_nhat, value); }
        }
        string fmo_ta;
        public string mo_ta
        {
            get { return fmo_ta; }
            set { SetPropertyValue<string>(nameof(mo_ta), ref fmo_ta, value); }
        }
        DateTime fngay_nhap;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime ngay_nhap
        {
            get { return fngay_nhap; }
            set { SetPropertyValue<DateTime>(nameof(ngay_nhap), ref fngay_nhap, value); }
        }
        ChiTietSanPham fid_chi_tiet_san_pham;
        [Association(@"LoHangReferencesChiTietSanPham")]
        public ChiTietSanPham id_chi_tiet_san_pham
        {
            get { return fid_chi_tiet_san_pham; }
            set { SetPropertyValue<ChiTietSanPham>(nameof(id_chi_tiet_san_pham), ref fid_chi_tiet_san_pham, value); }
        }
        [Association(@"ChiTietHoaDonReferencesLoHang")]
        public XPCollection<ChiTietHoaDon> ChiTietHoaDons { get { return GetCollection<ChiTietHoaDon>(nameof(ChiTietHoaDons)); } }
    }

}
