//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ShopQuanAoV2.Module.BusinessObjects.ORMDataModel1
{

    [DefaultProperty("ten")]
    public partial class NhaCungCap : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string ften;
        public string ten
        {
            get { return ften; }
            set { SetPropertyValue<string>(nameof(ten), ref ften, value); }
        }
        string fdien_thoai;
        public string dien_thoai
        {
            get { return fdien_thoai; }
            set { SetPropertyValue<string>(nameof(dien_thoai), ref fdien_thoai, value); }
        }
        string fdia_chi;
        public string dia_chi
        {
            get { return fdia_chi; }
            set { SetPropertyValue<string>(nameof(dia_chi), ref fdia_chi, value); }
        }
        [Association(@"LoHangReferencesNhaCungCap")]
        public XPCollection<LoHang> LoHangs { get { return GetCollection<LoHang>(nameof(LoHangs)); } }
    }

}
