//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ShopQuanAoV2.Module.BusinessObjects.ORMDataModel1
{

    [DefaultProperty("ten")]
    public partial class SanPham : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string ften;
        public string ten
        {
            get { return ften; }
            set { SetPropertyValue<string>(nameof(ten), ref ften, value); }
        }
        string fhinh_anh;
        public string hinh_anh
        {
            get { return fhinh_anh; }
            set { SetPropertyValue<string>(nameof(hinh_anh), ref fhinh_anh, value); }
        }
        string fhang;
        public string hang
        {
            get { return fhang; }
            set { SetPropertyValue<string>(nameof(hang), ref fhang, value); }
        }
        string fmo_ta;
        public string mo_ta
        {
            get { return fmo_ta; }
            set { SetPropertyValue<string>(nameof(mo_ta), ref fmo_ta, value); }
        }
        decimal fgia_thanh;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "#### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal gia_thanh
        {
            get { return fgia_thanh; }
            set { SetPropertyValue<decimal>(nameof(gia_thanh), ref fgia_thanh, value); }
        }
        long fton_kho;
        public long ton_kho
        {
            get { return fton_kho; }
            set { SetPropertyValue<long>(nameof(ton_kho), ref fton_kho, value); }
        }
        [Association(@"ChiTietSanPhamReferencesSanPham")]
        public XPCollection<ChiTietSanPham> ChiTietSanPhams { get { return GetCollection<ChiTietSanPham>(nameof(ChiTietSanPhams)); } }
    }

}
